### ISSUE TITLE
Where did we land on use of seeAlso?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#37]
Question on conference call today. Where did we fall on the issue linking data resources to non information resources? What's the logic for that decision specifically?

schema:subjectOf ...
https://github.com/opengeospatial/SELFIE/blob/master/docs/examples/meta-resource-1.jsonld#L52

**Comment by abhritchie** [comment]
The decision to use schema:subjectOf instead of seeAlso was made in the face-to-face at Quebec and riffed off the discussion for issue #19.

Ultimately
- seeAlso was too weak
- isDefinedBy was, by definition ... pun intended, too strong (giving statements in a representation authority they might not have)
- sameAs was redundant (all the statements being pulled together should have the same subject)

The last bit was informative and helped us make the decision to use subjectOf. If all the statements in the target representation are about the NIR then the NIR is the *subject of* the statements in that representation. We don't include the inverse schema:about in the target document because the \@id value is already doing that.

**Comment by KathiSchleidt** [comment]
Getting there, but as we still have sameAs in addition to subjectOf, still not quite satisfied. My attempt at paraphrasing Alistair:
- subjectOf: All observations where the subject of this observation is the NIR being described (so the NIR representation is somewhere it's FoI or Ufo hierarchy)
- sameAs: Alternative representations of the NIR being described

So - what did I get wrong this time? ;)

**Comment by dblodgett-usgs** [comment]
Based on discussion from the call on October 9th, we've decided that this is something we need to take up in future work and move on from for now. Going to close this and we will document in the ER. see #40 for documentation of the ER.
