### ISSUE TITLE
@type vs dctType

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/SELFIE#41]
Trying to mock up an Observation resource by comparing with the existing examples
I alternately find object types defined as @type or dctType
I cannot find a difference where one tag is used vs. the other - is there a plan here, or just random madness? ;)

**Comment by bsimons14** [comment]
I also don't understand when to use one or the other. Is there a pattern we should be following?

**Comment by abhritchie** [comment]
- @type is used to explicitly type a resource - this expects an available RDF representation
- dct:type is being replaced by foaf:primaryTopic (see #33). This is used to strongly suggest the type of target resource described by the document located at the url - the target resource may not have an RDF representation - e.g. it could be a GML doc, or or HTML page

Hopefully it will make more sense when the SELFIE resource model is better explained. Documentation to come ...

**Comment by bsimons14** [comment]
Updated CeRDI examples (SELFIE/docs/examples/) to (hopefully) be consistent with Aug 9 example at #33.

**Comment by KathiSchleidt** [comment]
Sorry for reopening, but after trawling through all issues (reason I did my little GitHub API Dump Script), I'm still lost ;(
My current confusion (all pertaining to the GeoJSON encoding) seems to have to do with the question of "To @ or not to @": I'm getting lost between id&type vs. @id&@type. Understanding to date:
- "id" directly under the properties is the URI of the NIR
- "@id" is (often) used in nested objects (gwAquiferSystem, sameAs), but at times "url" seems to serve a similar role
- "type" directly under the properties is the datatype of the spatial feature type corresponding to the NIR
- "@type" becomes a bit more ambiguous. In many cases, it's also the datatype(**S**) of the feature type being referenced (spatialCoverage, gwAquiferSystem, sameAs), but in others (subjectOf), it's foaf:Document with the datatype of the feature being provided in "primaryTopic" (or is the primaryTopic what the object referenced by the "url" considers as it's primaryTopic???)

**Comment by alpha-beta-soup** [comment]
If you're thinking about GeoJSON, remember that the GeoJSON vocabulary aliases `@type` as `type` (which in turn is defined as `rdfs:type`) and `@id` as `id`, so you actually need to run the JSON-LD through expansion rather than just read the keys.

HTML: https://geojson.org/geojson-ld/vocab.html
RDF: https://geojson.org/geojson-ld/vocab.rdf

**Comment by KathiSchleidt** [comment]
but, is there any logical reason why in the examples, times it's with @, times without? (within the same example)
I'm trying to figure if there is a syntax or semantic fine line I'm missing or if it's a typo!

**Comment by dblodgett-usgs** [comment]
Can you point to an example where you are seeing this?

**Comment by KathiSchleidt** [comment]
Starts at https://raw.githubusercontent.com/opengeospatial/SELFIE/master/docs/examples/meta-resource-1.geojson
seems to be consistent, thus I'm confused! ;)

**Comment by dblodgett-usgs** [comment]
Since this: https://geojson.org/geojson-ld/geojson-context.jsonld (referenced as the primary context of the docuemnt) maps `id` to `@id` everywhere you see `id` in that document it may as well be `@id`. If you go to: https://json-ld.org/playground/ and plug in the json-ld content you will see that all the instances of id get converted to `@id` in the expanded and flattened view.

On the subject of this issue -- at the end of the day, how we use @type and dct:Type is going to **require additional testing and experimentation** if it is to become part of a best practice or standard. Given that, take any examples you see in these documents to be evidence of experimentation, not concrete guidance on what to implement. 

To come full circle, we need to be careful to understand 
1) json-ld syntax / context expansion
2) the meaning / purpose of the rdf predicates we are using
3) what use cases we actually apply which predicates to

**Comment by dblodgett-usgs** [comment]
See recent conversation and repository updates. Closing this for now.
