### ISSUE TITLE
Guidelines for context creation - class aliases

### ISSUE THREAD

**Issue by abhritchie** [opengeospatial/SELFIE#53]
The write-up of ELFIE contexts should include some helpful guidelines for context creation. This is one of those things where we are dealing with a look-and-feel issue where consistency is nice to have, but not essential.

One thing I'd like feedback on is whether or not we need to alias class names in a context, e.g.:
``"Observation": "sosa:Observation"`` - could we use Compact URIs (CURIs) instead?

**Proposal**
Only base/namespace URI prefixs (e.g. ``"schema": "http://schema.org/"``) and property keys (e.g. ``"sameAs": "schema:sameAs"``) are aliased.  Classes are not, instead they are returned as compact URIs in the JSON documents: ``"@type": "gw:GW_HydrogeoUnit"``.

**Reason**
Base/namespace prefixes make life much easier, making URIs shorter and clearer in documents. ``gw:GW_Well`` is much nicer than ``https://www.opengis.net/def/gwml2#GW_Well``.

ELFIE made the decision not to use CURIs for property keys names to keep things simple [1]. The downside of this decision is we lose the ability to distinguish between the use of the same label in different (wait for it ... pun intended ...) contexts. CURIs are great disambiguators (``schema:comment``; ``rdfs:comment``) but this can be hacked around with longer key aliases (``"schemaComment": "schema:comment"``; ``"rdfsComment": "rdfs:comment"``).

It is worthwhile only hacking when we absolutely have to and this hack isn't necessary for classes (@type values) as they are property values. There should be no issues with escaping characters (like colons) don't apply. The other benefits of not aliasing classes are:

- Laziness: don't have to put the alias in the context, can just return the CURI value.
- Don't have to worry about globally unique aliases in contexts (provided care is taken defining the prefix).

[1] '*JSON keyword names are kept as simple as possible (i.e. no extended JSON-LD namespace prefixes). This should minimize “developer trauma” and also take into account the fact that some parsers don’t like colons in keywords, even though they are legitimate JSON.*' -- From [ELFIE, JSON-LD Context Files - File structure](https://opengeospatial.github.io/ELFIE/json-ld/).

**Comment by afeliachi** [comment]
If possible could we add  to the context creation discussion the "type coercion" issue that we postponed in ELFIE.

**Comment by afeliachi** [comment]
Regarding the proposal, I understand the confusion that could happen between a class name and a property name, but maybe it's not a sufficient reason to not alias classes. I think we should emphasize the use of CamlCase writing  for aliases with class names beginning with uppercase and properties begining with lowercase.
I think the type coercion could be helpful since it provides a bit of guidance on what are the properties in a context and how they should be used

**Comment by abhritchie** [comment]
The issue is not confusion between property names and class names. The examples of disambiguation provided were for two *properties* that could be confused (the ``comment`` property from schema.org and the ``comment`` property from RDFS. 

The proposal is for a more nuanced approach for *class* names, i.e. the values of ``@type`` are CURIs.

I'm not sure how type coercion helps for ``@type``.

**Comment by abhritchie** [comment]
A slightly expanded example from the proposal section in the issue text. (Hand crafted so please be patient with enny mitsakes!)
````json
{
  "@context": 
    {
      "schema": "http:schema.org/",
      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
      "gw": "https://www.opengis.net/def/gwml2#",
      "schemaComment": "schema:comment",
      "rdfsComment": "rdfs:comment"
    },
  "@id": "http://some.domain/id/thing",
  "@type": "gw:GW_HydrogeoUnit",
  "schemaComment": "A comment scoped to the schema.org definition.",
  "rdfsComment": "A comment scoped to the RDFS definition."
}
````
Under our current full aliasing approach the value of ``@type`` would be:
``"@type": "GW_HydrogeoUnit"``
the ``@context`` would therefore contain
``"GW_HydrogeoUnit": "gw:GW_HydrogeoUnit"``

**Comment by afeliachi** [comment]
I fully agree with you regarding the the properties aliasing. IMHO what you propose here is the best way to disambiguate similar properties names. 

In my comment I was referring to the fact that you proposed to alias only properties and not classes, maybe I misinterpreted your proposal?  

The reason I said there could be confusions between properties names and classes names is that I remember seeing in early stages of ELFIE examples some misusing of classes aliases as properties.
I understand that if everything is aliased in a context we can't distinguish a property from a class without looking into the ontology they belong to. My idea is that (in addition to camelCase rules) type coercion would help distinguishing properties aliases, since @type coercion is applied only to them. But then it was just an idea :)

**Comment by abhritchie** [comment]
Thanks @afeliachi ... I can be a bit slow sometimes. @type coercion on properties is well worth following up (ELFIE-3, or OGC API Features - Linked Data Extension).

**Comment by afeliachi** [comment]
I am sorry, am the one who didn't give a context (no pun intended) to my response.
I see what you mean here and I agree. It's much easier to avoid confusion between classes and properties this way i.e. aliasing only properties. 
In this case the user of the context should look into the ontologies to figure out the class names to use. We should precise that in the report I think.

ps: just for clarification, from what I understand, type coercion can be used for properties only, i.e. to specify the nature of the values of a given property  and how it should be interpreted. But as you said, it's a discussion for a following experimentation.

**Comment by dblodgett-usgs** [comment]
Will document in the Engineering Report

**Comment by dblodgett-usgs** [comment]
I just copied and rewrote the text from this issue here: https://docs.google.com/document/d/1b-TdqWl3jf2jJD7dYvLkxTa6JEGxtUJAue7jSiaEE2s/edit#bookmark=id.7k7pq05zjn92
