### ISSUE TITLE
Observation a NIR ?

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/SELFIE#70]
From discussion in Toulouse TC Impromptu session.
After ELFIE-1 & ELFIE-2 an Observation is a NIR.
Question is where to draw the line between NIR and DIR (ex : assigning URI vs URL to om:result).
We are back to the ISO O&M model, assigning URI to OM_Observation and om:result being xs:any

**Comment by abhritchie** [comment]
Addressing the question in the title of this issue:

Observations are non-information resources (in this case real-world _events_). This is not a result of any ELFIE, it is just how-it-is when we apply [the Range-14 view of the world](https://www.w3.org/2001/tag/doc/httpRange-14/2007-08-31/HttpRange-14.html), specifically how to handle a real-world thing's presence on the web.

Non-information resources can have digital representations that are referred to (in this context) as information resources. Dereferencing the HTTP URI that identifies the observation should result in a redirect to one or more URLs locating an information resource. Which URL you get (because there a likely to be several available information resources) is subject to a negotiation process. A process we are struggling, and failing, to describe in SELFIE. The notion of information resources being subtyped into meta-information resources (MIRs) and data information resources (DIRs) is part of an attempt to organise these negotiations.

My position, FWIW, is that the MIR and DIR sub-types are an unhelpful mistake.

So, in the context of an observation there is no line: Observations are assigned HTTP URIs and the assigner should make every effort to provide a re-direction mechanism that takes an agent to a/some information resource URLs.

I suspect I've just written a lot of words to tell you what you already know. To the second question ...

**Comment by abhritchie** [comment]
'Where to draw the line between NIR and DIR (ex : assigning URI vs URL to om:result)?'

Rewording it slightly: do we provide HTTP URIs (identifiers non-information resources) or URLs (locations of information resources) as the value of om:result?

The answer is not either or, but simply when it is appropriate for the observed property:
1. If the observation classifies something then use the HTTP URI of the classifier (the identifier a concept, a non-information resource).
2. If the observation result is another feature then use the HTTP URI of the feature (non-information resource).
3. If the result is a literal (like pH = 6) then provide the literal as the value. If it has some sort of structure then it is a blank node.
4. If the observation result is a digital artifact that is difficult or impossible to embed in the response (e.g. a coverage) then provide a URL to the file or service that provides the result.

I fear I'm missing something in your question. Does this make sense?

**Comment by dblodgett-usgs** [comment]
These answers are going in the engineering report.

I find these answers really clear and helpful. My one nit is that The MR and DR distinction isn't strictly wrong -- it's useful in the context of a specific implementation even if it is logically or conceptually dubious. We've stumbled over how far to take the distinction and clearly we took it too far and have had to pull it back a bit.

**Comment by sgrellet** [comment]
"I fear I'm missing something in your question. Does this make sense?"
Yes it does. And the answers corresponds to the one we had in Toulouse.
The purpose of that issue was to exactly to have this written down (and going to the ER).
We came to the conclusion here that there was a kind of implicit common (S)ELFIE understanding on how to treat observations. But that it was not clearly written anywhere thus creating confusion.
Thanks. Now we have to set up examples to illustrate :)

**Comment by dblodgett-usgs** [comment]
This is fodder for #40
