### ISSUE TITLE
Clarify selection of owl:sameAs over schema:sameAs

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#98]
Was this intentional?
https://opengeospatial.github.io/ELFIE/json-ld/elf.jsonld switched to owl:sameAs https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld

Concerns were raised on 2/25 call.

**Comment by abhritchie** [comment]
`xxx:sameAs` was introduced for the same-thing-in-multiple-repos use case. For example: data about the same Victorian borehole are held by both GSV and CERDI; here in NZ we have monitoring stations shared by regional authorities and utilities companies.
`sameAs` was proposed because it means exactly that: these information resources are describing _exactly the same thing_. `subjectOf` is ambiguous.
`owl:sameAs` is arguably appropriate valid in this use case - the graphs should be merged without concern - but the universally strong and emotional reaction to **`owl:`**`sameAs` shows `schema:sameAs` is safer ... and acceptable to this IE as logical consistency and inferencing are a secondary concern.

**Comment by dblodgett-usgs** [comment]
Should it be "same-thing-in-multiple-repos-with-different-non-information-identifiers" use case? `schema:subjectOf` takes care of the "same-thing-in-multiple-repos-using-shared-non-information-identifiers" right?

**Comment by abhritchie** [comment]
Not the way `subjectOf` is currently used.
